#!/usr/bin/env bash
# ============================================================================
# Railway test-server entrypoint for OpenEMR
# ============================================================================
# Runs before the upstream docker/release/openemr.sh and:
#   - refuses to start with missing or upstream-default credentials, so the
#     container never comes up with a public installer or admin/pass;
#   - seeds an empty Railway volume mounted on sites/ from the image copy;
#   - pins globals that would send mail, SMS/reminders or live payments to
#     inert values (re-applied on every boot by openemr.sh setGlobalSettings);
#   - optionally puts HTTP basic auth in front of everything except health.
#
# Never prints credential values. TEST USE ONLY - not approved for clinical use.
#
# @package   OpenEMR
# @link      https://www.open-emr.org
# @author    Craig Allen <craig@interconnected.au>
# @copyright Copyright (c) 2026 Craig Allen
# @license   https://github.com/openemr/openemr/blob/master/LICENSE GNU General Public License 3
# ============================================================================
set -euo pipefail

OE_ROOT="${OE_ROOT:-/var/www/localhost/htdocs/openemr}"
SITES_TEMPLATE_DIR="${SITES_TEMPLATE_DIR:-/swarm-pieces/sites}"
APACHE_CONF_DIR="${APACHE_CONF_DIR:-/etc/apache2/conf.d}"
SITES_OWNER="${SITES_OWNER:-apache:apache}"  # "none" skips chown (tests)
MIN_SECRET_LENGTH=16

refuse() {
    echo "REFUSING to start: $1" >&2
    exit 64
}

require_secret() {
    local name="$1" default="$2" value="${!1:-}"
    [[ -n "${value}" ]] || refuse "${name} is not set"
    [[ "${value}" != "${default}" ]] || refuse "${name} is the upstream default"
    [[ "${#value}" -ge "${MIN_SECRET_LENGTH}" ]] || refuse "${name} is shorter than ${MIN_SECRET_LENGTH} characters"
}

[[ -n "${MYSQL_HOST:-}" ]] || refuse "MYSQL_HOST is not set"
[[ "${MANUAL_SETUP:-no}" != "yes" ]] || refuse "MANUAL_SETUP=yes would expose the web installer"
[[ -n "${OE_USER:-}" && "${OE_USER}" != "admin" ]] || refuse "OE_USER must be set to a non-default name"
require_secret MYSQL_ROOT_PASS root
require_secret MYSQL_PASS openemr
require_secret OE_PASS pass

# Railway volumes start empty; give openemr.sh the default site to configure.
if [[ ! -f "${OE_ROOT}/sites/default/sqlconf.php" ]]; then
    echo "Seeding empty sites volume from image template"
    mkdir -p "${OE_ROOT}/sites"
    cp -a "${SITES_TEMPLATE_DIR}/." "${OE_ROOT}/sites/"
fi
if [[ "${SITES_OWNER}" != "none" ]]; then
    chown -R "${SITES_OWNER}" "${OE_ROOT}/sites"
fi

# Outbound mail, reminders, Direct messaging, portal and live payments off.
# SMTP points at the local discard port so nothing leaves the container.
SAFETY_SETTINGS=(
    EMAIL_METHOD=SMTP
    SMTP_HOST=127.0.0.1
    SMTP_PORT=9
    payment_gateway=InHouse
    gateway_mode_production=0
    medex_enable=0
    phimail_enable=0
    portal_onsite_two_enable=0
)
for setting in "${SAFETY_SETTINGS[@]}"; do
    export "OPENEMR_SETTING_${setting}"
    echo "safety: OPENEMR_SETTING_${setting}"
done

boundary_conf="${APACHE_CONF_DIR}/zz-railway-boundary.conf"
boundary_file="${APACHE_CONF_DIR}/railway-boundary.htpasswd"
if [[ -n "${OE_HTTP_BOUNDARY_PASS:-}" ]]; then
    require_secret OE_HTTP_BOUNDARY_PASS ""
    boundary_hash=$(printf '%s' "${OE_HTTP_BOUNDARY_PASS}" | openssl passwd -apr1 -stdin)
    umask 027
    printf '%s:%s\n' "${OE_HTTP_BOUNDARY_USER:-tester}" "${boundary_hash}" > "${boundary_file}"
    cat > "${boundary_conf}" <<EOF
# Generated by railway-start.sh: HTTP boundary for the test server.
<Location "/">
    AuthType Basic
    AuthName "OpenEMR test server"
    AuthUserFile "${boundary_file}"
    Require valid-user
</Location>
<Location "/meta/health">
    Require all granted
</Location>
EOF
    [[ "${SITES_OWNER}" = "none" ]] || chown "root:${SITES_OWNER#*:}" "${boundary_file}"
    echo "HTTP boundary enabled"
else
    rm -f "${boundary_conf}" "${boundary_file}"
fi

if [[ "${RAILWAY_START_CHECK_ONLY:-0}" = "1" ]]; then
    echo "check only: not starting OpenEMR"
    exit 0
fi

cd "${OE_ROOT}"
exec ./openemr.sh
